-- MySQL Script generated by MySQL Workbench
-- Fri Feb  7 15:28:46 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Equipe498866
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Equipe498866` ;

-- -----------------------------------------------------
-- Schema Equipe498866
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Equipe498866` DEFAULT CHARACTER SET utf8 ;
USE `Equipe498866` ;

-- -----------------------------------------------------
-- Table `agencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `agencia` ;

CREATE TABLE IF NOT EXISTS `agencia` (
  `num_ag` INT NOT NULL AUTO_INCREMENT,
  `nome_ag` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `sal_total` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`num_ag`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cliente` ;

CREATE TABLE IF NOT EXISTS `cliente` (
  `cpf` CHAR(11) NOT NULL,
  `nome_comp` VARCHAR(150) NOT NULL,
  `rg` VARCHAR(15) NOT NULL,
  `orgao_emissor` VARCHAR(20) NOT NULL,
  `uf` CHAR(2) NOT NULL,
  `data_nasc` DATE NOT NULL,
  PRIMARY KEY (`cpf`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  UNIQUE INDEX `rg_UNIQUE` (`rg` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cliente_has_conta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cliente_has_conta` ;

CREATE TABLE IF NOT EXISTS `cliente_has_conta` (
  `cliente_cpf` CHAR(11) NOT NULL,
  `conta_num_conta` INT NOT NULL,
  `agencia_num_ag` INT NOT NULL,
  PRIMARY KEY (`cliente_cpf`, `conta_num_conta`, `agencia_num_ag`),
  INDEX `fk_cliente_has_conta_conta1_idx` (`conta_num_conta` ASC) VISIBLE,
  INDEX `fk_cliente_has_conta_agencia1_idx` (`agencia_num_ag` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `conta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `conta` ;

CREATE TABLE IF NOT EXISTS `conta` (
  `num_conta` INT NOT NULL AUTO_INCREMENT,
  `saldo` REAL UNSIGNED NOT NULL,
  `senha` VARCHAR(45) NOT NULL DEFAULT 'criptografada',
  `tipo_conta` ENUM('conta-corrente', 'poupança', 'conta especial') NOT NULL,
  `juros` DECIMAL(5,2) NULL,
  `limite_credito` DECIMAL(10,2) NULL,
  `data_aniversario` DATE NULL,
  `gerente_matricula` INT NOT NULL,
  PRIMARY KEY (`num_conta`),
  UNIQUE INDEX `num_conta_UNIQUE` (`num_conta` ASC) VISIBLE,
  INDEX `fk_conta_funcionario1_idx` (`gerente_matricula` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dependente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dependente` ;

CREATE TABLE IF NOT EXISTS `dependente` (
  `id_dep` INT NOT NULL AUTO_INCREMENT,
  `matricula` INT NOT NULL,
  `nome_comp` VARCHAR(150) NOT NULL,
  `data_nas` DATE NOT NULL,
  `idade` INT NOT NULL,
  `parentesco` ENUM('filho(a)', 'cônjuge', 'genitor(a)') NOT NULL,
  PRIMARY KEY (`id_dep`, `matricula`),
  INDEX `fk_dependente_funcionario1_idx` (`matricula` ASC) VISIBLE,
  UNIQUE INDEX `nome_comp_UNIQUE` (`nome_comp` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `email_cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `email_cliente` ;

CREATE TABLE IF NOT EXISTS `email_cliente` (
  `id_email` INT NOT NULL AUTO_INCREMENT,
  `cliente_cpf` CHAR(11) NOT NULL,
  `email` VARCHAR(254) NOT NULL,
  `tipo_email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_email`, `cliente_cpf`),
  INDEX `fk_email_cliente_cliente1_idx` (`cliente_cpf` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `endereco` ;

CREATE TABLE IF NOT EXISTS `endereco` (
  `id_end` INT NOT NULL AUTO_INCREMENT,
  `cliente_cpf` CHAR(11) NOT NULL,
  `tipo_log` VARCHAR(45) NOT NULL,
  `rua` VARCHAR(100) NOT NULL,
  `num` INT NOT NULL,
  `bairro` VARCHAR(100) NOT NULL,
  `cep` CHAR(10) NOT NULL,
  `cidade` VARCHAR(100) NOT NULL,
  `estado` CHAR(2) NOT NULL,
  PRIMARY KEY (`id_end`, `cliente_cpf`),
  INDEX `fk_endereco_cliente1_idx` (`cliente_cpf` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `funcionario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `funcionario` ;

CREATE TABLE IF NOT EXISTS `funcionario` (
  `matricula` INT NOT NULL AUTO_INCREMENT,
  `num_ag` INT NOT NULL,
  `nome_comp` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(45) NOT NULL DEFAULT 'criptografada',
  `endereço` VARCHAR(100) NOT NULL,
  `cidade` VARCHAR(80) NOT NULL,
  `cargo` ENUM('gerente', 'atendente', 'caixa') NOT NULL,
  `genero` ENUM('masculino', 'feminino', 'não-binário') NOT NULL,
  `data_nasc` DATE NOT NULL,
  `salario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`matricula`),
  INDEX `fk_funcionario_agencia_idx` (`num_ag` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `telefone_cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `telefone_cliente` ;

CREATE TABLE IF NOT EXISTS `telefone_cliente` (
  `id_tel` INT NOT NULL AUTO_INCREMENT,
  `cliente_cpf` CHAR(11) NOT NULL,
  `telefone` VARCHAR(11) NOT NULL,
  `tipo_tel` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tel`, `cliente_cpf`),
  INDEX `fk_telefone_cliente_cliente1_idx` (`cliente_cpf` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `transacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `transacao` ;

CREATE TABLE IF NOT EXISTS `transacao` (
  `num_transacao` INT NOT NULL AUTO_INCREMENT,
  `conta_num_conta` INT NOT NULL,
  `tipo_transacao` ENUM('saque', 'deposito', 'pagamento', 'estorno', 'transferencia', 'PIX') NOT NULL,
  `data_hora` VARCHAR(45) NOT NULL,
  `valor` REAL NOT NULL,
  PRIMARY KEY (`num_transacao`, `conta_num_conta`),
  UNIQUE INDEX `num_transacao_UNIQUE` (`num_transacao` ASC) VISIBLE,
  INDEX `fk_transacao_conta1_idx` (`conta_num_conta` ASC) VISIBLE)
ENGINE = InnoDB;

  select * from `agencia`;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

